#include <metal_stdlib>

using namespace metal;

// Handwritten MSL used only to probe the host toolchain. This file is not
// generated by Mojo and the probe never loads or dispatches it.
kernel void mojo_ios_air_probe(
    device const float *lhs [[buffer(0)]],
    device const float *rhs [[buffer(1)]],
    device float *result [[buffer(2)]],
    uint index [[thread_position_in_grid]]
) {
    result[index] = lhs[index] + rhs[index];
}
