// Artifact-only consumer for the Simulator slice generated by
// run_xcframework_smoke.sh. The executable is never signed, installed, or run.

import MojoIOSSmoke

@main
struct MojoIOSSmokeXCFrameworkConsumer {
    static func main() {
        precondition(mojo_add(20, 22) == 42)
    }
}
